version: "3.9"

services:
  migrator:
    build:
      context: .
      target: migrator
    container_name: migrator
    restart: "no"
    environment:
      DBHOST: ${PG_HOST}
      DBUSER: ${PG_USER}
      DBPASSWORD: ${PG_PASSWORD}
      DBNAME: ${PG_DATABASE}
      DBPORT: ${PG_PORT}
    env_file:
      - .env
    
  processor:
    build:
      context: .
      target: processor-production
    container_name: processor
    restart: "unless-stopped"
    env_file:
      - .env

  consumer:
    build:
      context: .
      target: consumer-production
    container_name: consumer
    restart: "unless-stopped"
    env_file:
      - .env
    depends_on:
      - migrator

  api:
    build:
      context: .
      target: api-production
    container_name: api
    restart: "unless-stopped"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://api:${PORT}/health || exit 1
      interval: 30s
      retries: 5
      timeout: 10s
    ports:
      - 127.0.0.1:${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - migrator
