server:
  port: 3000
  host: 127.0.0.1
  auth:
    username: admin
    password: password

db:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  database: Messages-api

kafka:
  brokers:
    - 127.0.0.1:9092
  topic: messages
